apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deploy
  labels:
    app: comments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments-cont
          image: wildbohana/comments:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: comments-configmap
            - secretRef:
                name: comments-secret